### ISSUE TITLE
Tutorial link is dead

### ISSUE THREAD

**Issue by ski** [substrate-developer-hub/tcr-substrate#2]
The link pointing to the tutorial is a 404 now.  Do you have a backup of the tutorial itself somewhere?

**Comment by JoshOrndorff** [comment]
Thank you for reporting this. The TCR tutorial was for a much older version of Substrate. In this repo the code is updated (somewhat) but the tutorial was not.

There are lots of good tutorials at substrate.dev/tutorials though.

I've removed the broken link. Thanks for reporting.
